import openai
from github import Github
import os

# OpenAI APIキーの設定
openai.api_key = os.getenv("OPENAI_API_KEY")

def generate_review_findings(branch):
    """
    Generate code review findings using ChatGPT in Japanese.

    Args:
        branch (str): The branch being reviewed.

    Returns:
        list: A list of review findings generated by ChatGPT in Japanese.
    """
    # ChatGPTに日本語でレビューを依頼するメッセージ
    prompt = f"""
    あなたはコードレビュアーです。次のブランチ `{branch}` に対するコードレビューをお願いします。
    変数名、コードの構造、最適化の提案を含む3つのレビューコメントを箇条書きで教えてください。
    """

    # OpenAI APIを使ってレビュー内容を生成
    response = openai.Completion.create(
        model="text-davinci-003",  # モデルを選択
        prompt=prompt,
        max_tokens=200,
        temperature=0.5
    )

    # ChatGPTの応答からレビュー内容を抽出
    findings = response.choices[0].text.strip().split("\n")
    
    return findings

def create_review_issue(github_token, repository, branch, findings):
    """
    Create a GitHub Issue with code review findings.

    Args:
        github_token (str): GitHub access token.
        repository (str): The repository in "owner/repo" format.
        branch (str): The branch being reviewed.
        findings (list): A list of review comments.
    """
    # Authenticate with GitHub
    g = Github(github_token)
    
    # Access the repository
    repo = g.get_repo(repository)
    
    # Format the issue title and body
    issue_title = f"ブランチ `{branch}` のコードレビュー結果"
    issue_body = "### コードレビューで発見された問題:\n"
    for finding in findings:
        issue_body += f"- {finding}\n"

    # Create the issue
    issue = repo.create_issue(
        title=issue_title,
        body=issue_body
    )
    
    print(f"Issue created: {issue.html_url}")


if __name__ == "__main__":
    # Retrieve environment variables
    GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
    REPOSITORY = os.getenv("REPOSITORY")  # e.g., "your-username/your-repository-name"
    BRANCH = os.getenv("BRANCH")          # e.g., "main"
    
    # ChatGPTを使ってレビュー指摘事項を生成
    review_findings = generate_review_findings(BRANCH)
    
    # GitHub Issue を作成
    create_review_issue(GITHUB_TOKEN, REPOSITORY, BRANCH, review_findings)
