name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Cache SonarCloud
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonar-

      - name: Run SonarCloud Scan
        id: sonarcloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=crazymaki_training-note
            -Dsonar.organization=your-organization-key
            -Dsonar.host.url=https://sonarcloud.io

      - name: Check if SonarCloud scan was successful
        id: check-sonarcloud-status
        run: |
          if [ $? -eq 0 ]; then
            echo "SonarCloud scan was successful."
          else
            echo "SonarCloud scan failed."
            exit 1
          fi

      - name: Create GitHub Issue for successful scan
        if: success() # スキャンが成功した場合のみ実行
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title": "SonarCloud Scan Successful", "body": "SonarCloudのスキャンが正常に完了しました。問題はありません。"}' \
            https://api.github.com/repos/${{ github.repository }}/issues
