name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Java 17 のセットアップ
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      # Javaバージョン確認（オプション）
      - name: Verify Java version
        run: java -version

      # SonarCloud スキャンを実行
      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=crazymaki_training-note
            -Dsonar.organization=your-organization-key
            -Dsonar.host.url=https://sonarcloud.io
