name: Branch Commit Review
on:
  push:
    branches:
      - main # 対象のブランチ

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout Code
        uses: actions/checkout@v2

      # Python 環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      # 依存関係をインストール
      - name: Install dependencies
        run: pip install -r requirements.txt

      # スクリプトを実行
      - name: Run Review Script
        run: python scripts/code_review_script.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
